out_dir: tests/results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: mlff
  entity: daniel-rothenpieler-technical-university-of-munich
dataset:
  format: torch_geometric
  name: md17
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Embedding+MagLapPE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_MagLapPE:
  enable: True
  positional_encoding: True
  dim_pe: 8
  q: 0.
  largest_connected_component: False
  sparse: False
  max_freqs: 150
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,21)
  model: Linear
  dim_pe: 28
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: s2gnn
  loss_fun: l2
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: mlp_graph
  layers_pre_mp: 0
  layers_mp: 3
  layers_post_mp: 3
  dim_inner: 224
  layer_type: gcnconv
  use_edge_attr: True
  stage_type: stack
  batchnorm: False
  act: gelu
  dropout: 0.25
  agg: sum
  spectral:
    layer_skip: [3]
    frequency_cutoff: 1.0
    filter_encoder: basis # basis, lin, mlp or attn
    feature_transform: glu_0.05
    filter_variant: None  # None, silu or silu_mix
    # filter_layers: 0
    window: tukey
    basis_num_gaussians: 60
    basis_bottleneck: 0.2
    num_heads_filter_encoder: 128
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0035
  base_lr: 0.00225
  model_averaging: ema
  max_epoch: 250
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
share:
  dim_in: 236
device: cpu
